// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_38TDHp1DhpBo9gaZG-1YXeczL9g5q7M',
    appId: '1:210836512724:android:5aef0b82f682d4a8e54041',
    messagingSenderId: '210836512724',
    projectId: 'ai-psychology-balance',
    storageBucket: 'ai-psychology-balance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBToBLBd_q_1VqkAUp7ZXwYlYrpHhvLb4U',
    appId: '1:210836512724:ios:5aa61e34647ba844e54041',
    messagingSenderId: '210836512724',
    projectId: 'ai-psychology-balance',
    storageBucket: 'ai-psychology-balance.firebasestorage.app',
    androidClientId: '210836512724-b0f71btcirlbmnfb0kn78gu82rqjgdmh.apps.googleusercontent.com',
    iosClientId: '210836512724-8pk1ikmrg78ev7dl2d17a48bjk5hvhdc.apps.googleusercontent.com',
    iosBundleId: 'com.aipsychologybalance',
  );

}